"""empty message

Revision ID: 4e35df7a625b
Revises: ab07e41566ed
Create Date: 2019-07-24 16:57:49.726945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e35df7a625b'
down_revision = 'ab07e41566ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('send_frequency', sa.String(), nullable=True))
    op.add_column('users', sa.Column('send_method', sa.String(), nullable=True))
    op.add_column('users', sa.Column('sending_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sending_status')
    op.drop_column('users', 'send_method')
    op.drop_column('users', 'send_frequency')
    # ### end Alembic commands ###
